import Head from 'next/head'
import React from 'react'
import Link from 'next/link'

const nosotros = () => {
  return (
    <div>
      <Head>
        <title>CreaTextil - Nosotros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>desde nosotros</h1>
      <a Link href="/">
        ir Inicio
      </a>
    </div>
  );
}

export default nosotros